micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    login-handler: bearer
---
jackson:
    bean-introspection-module: true
